name:                formark
version:             0.1.0.0
github:              "dk949/formark"
license:             BSD3
author:              "dk949"
maintainer:          "dk949.david@gmail.com"
copyright:           "2021 dk949"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Formatter for Markdown
category:            Markdown

# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dk949/formark#readme>

dependencies:
- base >=4.5.0
- text
- parsec
- pandoc
- data-default
- regex-compat
- optparse-applicative

executables:
  formark-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
