
name: Main

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.stack/
          key: ${{ runner.os }}-stack

      - name: Setup haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: 'latest'

      - name: Build
        run: stack build --local-bin-path build/ --copy-bins

      - name: Package
        run: 7z a ${{ github.workspace }}/build/formark-${{ runner.os }}.zip ${{ github.workspace }}/build/formark

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/ChangeLog.md
          files: ${{ github.workspace }}/build/formark-${{ runner.os }}.zip
